
---
title: "Boxplots AMR classes"
author: "Casper Sahl Poulsen"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      results = "hold", 
                      warning = FALSE, 
                      message = FALSE,
                      fig.align = "center")
```

## Introduction
Creating Boxplots of AMR classes

### Packages
```{r}
library(ggplot2) #Data visualization, based on grammar of graphics. help(package="ggplot2")  
library(stringr) #Simple, consistent wrappers for common string operations. Like the str_replace function. help(package="stringr")
library(dplyr) #A grammar of data manipulation. A fast, consistent tool for working with data frame like objects. help(package="dplyr")
```

## Define variables
```{r}
#Subset data pig feces 1 and 2 (P1, P2), Sewage 1 and 2 (S1, S2), or spiked unspiked
Subset<-"All" #All, Allspiked, Allunspiked, PF, SW, P1, P1spiked, P1unspiked, P2, P2spiked, P2unspiked, S1, S1spiked, S1unspiked, S2, S2spiked, S2unspiked 

#Subset experiment, Experiment_Type. (Meaningfull combinations of subset and SubExp: HX=All, FTX=P1&S1, LTX=P1&S1, LPSX=All unspiked, HXFTX=P1&S1, HXLTX=P1&S1, HXLPSX=All unspiked, HXLTXLPSX=P1&S1 unspiked)
SubExp<-"HX" #HX, FTX, LTX, LPSX, HXFTX, HXLTX, HXLPSX, HXLTXLPSX, HXFTXLTX, All 

#Subset Frozen Unfrozen
SubFre<-"Both" #Frozen, Unfrozen, Both
```


## Analysis
### 1 Read in data
```{r}
AMRClass <- read.delim(file="AMRFPKMBacaggClass20180919.txt", check.names=FALSE, stringsAsFactors=FALSE, strip.white=TRUE)
Metadata <- read.delim(file="Metadata20180925.txt", check.names=FALSE, stringsAsFactors=FALSE, strip.white=TRUE)
```

### 2 Subsetting
```{r}
#Removing negative and positive controls
Metadata<-filter(Metadata, Sample_type_simple=="Sample")

#Subsetting metadata
if (Subset=="Allspiked") {
  Metadata<-filter(Metadata, SpikedUnspiked == "Spiked")
} else if (Subset=="Allunspiked") {
  Metadata<-filter(Metadata, SpikedUnspiked == "Unspiked")
} else if (Subset=="PF") {
  Metadata<-filter(Metadata, Experiment == "Pig_feces_1" | Experiment == "Pig_feces_2")
} else if (Subset=="SW") {
  Metadata<-filter(Metadata, Experiment == "Sewage_1" | Experiment == "Sewage_2")
} else if (Subset=="P1") {
  Metadata<-filter(Metadata, Experiment == "Pig_feces_1")
} else if (Subset=="P1spiked") {
  Metadata<-filter(Metadata, Sample_type == "Pig_feces_1_spiked")
} else if (Subset=="P1unspiked") {
  Metadata<-filter(Metadata, Sample_type == "Pig_feces_1")
} else if (Subset=="P2") {
  Metadata<-filter(Metadata, Experiment == "Pig_feces_2")
} else if (Subset=="P2spiked") {
  Metadata<-filter(Metadata, Sample_type == "Pig_feces_2_spiked")
} else if (Subset=="P2unspiked") {
  Metadata<-filter(Metadata, Sample_type == "Pig_feces_2")
} else if (Subset=="S1") {
  Metadata<-filter(Metadata, Experiment == "Sewage_1")
} else if (Subset=="S1spiked") {
  Metadata<-filter(Metadata, Sample_type == "Sewage_1_spiked")
} else if (Subset=="S1unspiked") {
  Metadata<-filter(Metadata, Sample_type == "Sewage_1")
} else if (Subset=="S2") {
  Metadata<-filter(Metadata, Experiment == "Sewage_2")
} else if (Subset=="S2spiked") {
  Metadata<-filter(Metadata, Sample_type == "Sewage_2_spiked")
} else if (Subset=="S2unspiked") {
  Metadata<-filter(Metadata, Sample_type == "Sewage_2")
} else if (Subset=="All") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Further subsetting metadata
if (SubExp=="HX") {
  Metadata<-filter(Metadata, Experiment_type == "Handling_experiment")
} else if (SubExp=="FTX") {
  Metadata<-filter(Metadata, Experiment_type == "Freeze_thaw_experiment")
} else if (SubExp=="LTX") {
  Metadata<-filter(Metadata, Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="LPSX") {
  Metadata2<-filter(Metadata, Experiment_type == "Library_prep_seq_platform_experiment")
  VectorLPSX <- unique(Metadata2$Matching_samples)
  Metadata<-filter(Metadata, Matching_samples %in% VectorLPSX)
  rm(VectorLPSX, Metadata2)
} else if (SubExp=="HXFTX") {
  Metadata<-filter(Metadata, Experiment_type == "Handling_experiment" | Experiment_type == "Freeze_thaw_experiment")
} else if (SubExp=="HXLTX") {
  Metadata<-filter(Metadata, Experiment_type == "Handling_experiment" | Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="HXLPSX") {
  Metadata<-filter(Metadata, Experiment_type == "Handling_experiment" | Experiment_type == "Library_prep_seq_platform_experiment")
} else if (SubExp=="HXLTXLPSX") {
  Metadata<-filter(Metadata, Experiment_type == "Handling_experiment" | Experiment_type == "Long_term_storage_experiment" | Experiment_type == "Library_prep_seq_platform_experiment")
} else if (SubExp=="HXFTXLTX") {
  Metadata<-filter(Metadata, Experiment_type == "Handling_experiment" | Experiment_type == "Freeze_thaw_experiment" | Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="All") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Further subsetting metadata
if (SubFre=="Frozen") {
  Metadata<-filter(Metadata, FrozenUnfrozenSimple == "Freezer")
} else if (SubFre=="Unfrozen") {
  Metadata<-filter(Metadata, FrozenUnfrozenSimple == "Unfrozen")
} else if (SubFre=="Both") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Applying subsetting to OTU tables 
AMRClass<-select(AMRClass, one_of(Metadata$Sample))
```



### 3 Create list of boxplots
```{r}
SelOrgs<-rownames(AMRClass)
tTaxSelect<-select(as.data.frame(t(AMRClass)), one_of(c(SelOrgs)))
tTaxSelect<-add_rownames(tTaxSelect, "Sample")
Plotting<-merge(Metadata, tTaxSelect, by="Sample")
Plotting$Replicate_Boxplot<-as.factor(Plotting$Replicate_Boxplot)
#Change order on x-axis
levels(Plotting$Replicate_Boxplot)
Plotting$Replicate_Boxplot<-ordered(Plotting$Replicate_Boxplot, levels=c("0h", "16h-80C", "64h-80C", "16h-20C", "64h-20C", "16h5C", "64h5C", "16h22C", "64h22C"))

#Might have issues with special characters, so this chunk might be needed
SelOrgs<-str_replace(SelOrgs, "-","")
colnames(Plotting) <- str_replace(colnames(Plotting),"-","")
#levels(Metadata$Sample_type)

#Make empty list for storing data
BoxplotListClass <- list()

#Plot
for (i in SelOrgs) {
  pdf(paste("BOXTSS", "Genus", Subset, SubExp, i, ".pdf", sep=""))
  print(ggplot(Plotting, aes_string(x="Replicate_Boxplot", y=i, group="Replicate_Boxplot")) +
          geom_boxplot(aes(fill=Replicate_Boxplot)) + facet_grid(Sample_type ~ ., scales="free") +
          ggtitle(paste("Genus", Subset, SubExp, i, sep=" ")) + 
          xlab("Storage conditions") + 
          ylab("Counts total sum scaled") + 
          theme_bw() + 
          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) + 
          scale_fill_manual(values=c("#999999", "#0571b0", "#0571b0", "#92c5de", "#92c5de", "#f4a582", "#f4a582", "#ca0020", "#ca0020")))
  dev.off()
  
BoxplotListClass[[i]] <- ggplot(Plotting, aes_string(x="Replicate_Boxplot", y=i, group="Replicate_Boxplot")) +
          geom_boxplot(aes(fill=Replicate_Boxplot)) + facet_grid(Sample_type ~ ., scales="free") +
          ggtitle(i) + 
          xlab("Storage conditions") + 
          ylab("Counts total sum scaled") + 
          theme_bw() + 
          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1), legend.position="none", strip.text.y = element_blank(), axis.title.x=element_blank(), axis.title.y=element_blank()) + 
          scale_fill_manual(values=c("#999999", "#0571b0", "#0571b0", "#92c5de", "#92c5de", "#f4a582", "#f4a582", "#ca0020", "#ca0020"))
}
```

### 4 Create figure
```{r}
#Have the plots stored in lists
lay <- rbind(c(1,2,3,4,5))
pdf(paste("SF15ClassAMR1.pdf", sep=""), width=8.5, height=11.75)
grid.arrange(BoxplotListClass$Tetracycline, BoxplotListClass$Macrolide, BoxplotListClass$Betalactam, BoxplotListClass$Aminoglycoside, BoxplotListClass$Lincosamide, layout_matrix = lay)
#grid.text("pig feces 1 unspiked", x=0, y=0, just="left", rot=1)
dev.off()

pdf(paste("ClassAMR2.pdf", sep=""), width=8.5, height=11.75)
grid.arrange(BoxplotListClass$Vancomycin, BoxplotListClass$Sulphonamide, BoxplotListClass$Phenicol, BoxplotListClass$Colistin, BoxplotListClass$Quinolone, layout_matrix = lay)  
dev.off()

pdf(paste("ClassAMR3.pdf", sep=""), width=8.5, height=11.75)
grid.arrange(BoxplotListClass$Fluoroquinolone, BoxplotListClass$Fosfomycin, BoxplotListClass$metronidazole, BoxplotListClass$Rifampicin, BoxplotListClass$Streptogramin, layout_matrix = lay)  
dev.off()

lay <- rbind(c(1,2))
pdf(paste("ClassAMR4.pdf", sep=""), width=3.4, height=11.75)
grid.arrange(BoxplotListClass$Trimethoprim, BoxplotListClass$No, layout_matrix = lay)  
dev.off()
```

## Additional
### Session information
```{r session_info}
sessionInfo()
```

### This document was processed on: 
```{r}
Sys.Date()
```
`
