
---
title: "Rank abundance curves"
author: "Casper Sahl Poulsen"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      results = "hold", 
                      warning = FALSE, 
                      message = FALSE,
                      fig.align = "center")
```

## Introduction
Creating rank abundance curves.

### Packages
```{r}
library(BiodiversityR) #Check for message behind R. Some utility functions (often based on the vegan package) for statistical analysis of biodiversity and ecological communities... . help(BiodiversityR)
library(dplyr) #A grammar of data manipulation. A fast, consistent tool for working with data frame like objects. help(package="dplyr")
```

## Define variables
```{r}
#Subset data pig feces 1 and 2 (P1, P2), Sewage 1 and 2 (S1, S2), or spiked unspiked
Subset<- c("P1unspiked", "P2unspiked", "S1unspiked", "S2unspiked", "P1spiked", "P2spiked", "S1spiked", "S2spiked") #All, Allspiked, Allunspiked, PF, SW, P1, P1spiked, P1unspiked, P2, P2spiked, P2unspiked, S1, S1spiked, S1unspiked, S2, S2spiked, S2unspiked 

#Subset experiment, Experiment_Type. (Meaningfull combinations of subset and SubExp: HX=All, FTX=P1&S1, LTX=P1&S1, LPSX=All unspiked, HXFTX=P1&S1, HXLTX=P1&S1, HXLPSX=All unspiked, HXLTXLPSX=P1&S1 unspiked)
SubExp<-"HX" #HX, FTX, LTX, LPSX, HXFTX, HXLTX, HXLPSX, HXLTXLPSX, HXFTXLTX, All 

#Subset Frozen Unfrozen
SubFre<-"Both" #Frozen, Unfrozen, Both

#Organism to include in plot, Remember has to be one of the most abundant
#Org<-Prevotella #Prevotella does not work input needs to be Prevotella not "Prevotella"
```


## Analysis
### 1 Read in data
```{r}
Tax <- read.delim(file="Taxonomy20180925.txt", check.names=FALSE, stringsAsFactors=FALSE, strip.white=TRUE)
Metadata <- read.delim(file="Metadata20180925.txt", check.names=FALSE, stringsAsFactors=FALSE, strip.white=TRUE)
```

### 2 Subsetting and create figure
```{r}
pdf(paste("SF3RAC", ".pdf", sep=""))
par(mfrow=c(2,4))
for (i in Subset) {
  
#Removing negative and positive controls
Metadata2<-filter(Metadata, Sample_type_simple=="Sample")

#Subsetting Metadata2
if (i=="Allspiked") {
  Metadata2<-filter(Metadata2, SpikedUnspiked == "Spiked")
} else if (i=="Allunspiked") {
  Metadata2<-filter(Metadata2, SpikedUnspiked == "Unspiked")
} else if (i=="PF") {
  Metadata2<-filter(Metadata2, Experiment == "Pig_feces_1" | Experiment == "Pig_feces_2")
} else if (i=="SW") {
  Metadata2<-filter(Metadata2, Experiment == "Sewage_1" | Experiment == "Sewage_2")
} else if (i=="P1") {
  Metadata2<-filter(Metadata2, Experiment == "Pig_feces_1")
} else if (i=="P1spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_1_spiked")
} else if (i=="P1unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_1")
} else if (i=="P2") {
  Metadata2<-filter(Metadata2, Experiment == "Pig_feces_2")
} else if (i=="P2spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_2_spiked")
} else if (i=="P2unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_2")
} else if (i=="S1") {
  Metadata2<-filter(Metadata2, Experiment == "Sewage_1")
} else if (i=="S1spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_1_spiked")
} else if (i=="S1unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_1")
} else if (i=="S2") {
  Metadata2<-filter(Metadata2, Experiment == "Sewage_2")
} else if (i=="S2spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_2_spiked")
} else if (i=="S2unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_2")
} else if (i=="All") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Further subsetting Metadata2
if (SubExp=="HX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment")
} else if (SubExp=="FTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Freeze_thaw_experiment")
} else if (SubExp=="LTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="LPSX") {
  Metadata22<-filter(Metadata2, Experiment_type == "Library_prep_seq_platform_experiment")
  VectorLPSX <- unique(Metadata22$Matching_samples)
  Metadata2<-filter(Metadata2, Matching_samples %in% VectorLPSX)
  rm(VectorLPSX, Metadata22)
} else if (SubExp=="HXFTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Freeze_thaw_experiment")
} else if (SubExp=="HXLTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="HXLPSX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Library_prep_seq_platform_experiment")
} else if (SubExp=="HXLTXLPSX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Long_term_storage_experiment" | Experiment_type == "Library_prep_seq_platform_experiment")
} else if (SubExp=="HXFTXLTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Freeze_thaw_experiment" | Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="All") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Further subsetting Metadata2
if (SubFre=="Frozen") {
  Metadata2<-filter(Metadata2, FrozenUnfrozenSimple == "Freezer")
} else if (SubFre=="Unfrozen") {
  Metadata2<-filter(Metadata2, FrozenUnfrozenSimple == "Unfrozen")
} else if (SubFre=="Both") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Applying subsetting to OTU tables 
Tax2<-select(Tax, one_of(Metadata2$Sample))

#5.1 collapse analysis to P1... by removing spiked in orgs. 
##Remove spiked in orgs at genus level
#SpikedGenus<-c("Escherichia", "Bacteroides", "Salmonella", "Fusobacterium", "Propionibacterium", "Staphylococcus", "Cryptosporidium", "Saccharomyces")
#Tax2$Orgs<-rownames(Tax2)
#Tax2<-Tax2[!Tax2$Orgs %in% SpikedGenus, ]
#Tax2<-Tax2[, 1:length(Tax2)-1]

#Remake proportions
#Tax2<-sweep(Tax2, 2, colSums(Tax2), FUN="/")

RankAbun.1 <- rankabundance(t(Tax2))
RankAbun.1
write.table(data.frame(RankAbun.1), file=paste(i, "Rank", "Genus", ".txt", sep=""), sep="\t", dec=",", row.names = T, quote = F)

#Create RACplot
rankabunplot(RankAbun.1, scale='proportion', addit=FALSE, specnames=c(1,2,3), xlim=c(0,60), main=i)


}
dev.off()



png(paste("SF3RAC", ".png", sep=""))
par(mfrow=c(2,4))
for (i in Subset) {
  
#Removing negative and positive controls
Metadata2<-filter(Metadata, Sample_type_simple=="Sample")

#Subsetting Metadata2
if (i=="Allspiked") {
  Metadata2<-filter(Metadata2, SpikedUnspiked == "Spiked")
} else if (i=="Allunspiked") {
  Metadata2<-filter(Metadata2, SpikedUnspiked == "Unspiked")
} else if (i=="PF") {
  Metadata2<-filter(Metadata2, Experiment == "Pig_feces_1" | Experiment == "Pig_feces_2")
} else if (i=="SW") {
  Metadata2<-filter(Metadata2, Experiment == "Sewage_1" | Experiment == "Sewage_2")
} else if (i=="P1") {
  Metadata2<-filter(Metadata2, Experiment == "Pig_feces_1")
} else if (i=="P1spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_1_spiked")
} else if (i=="P1unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_1")
} else if (i=="P2") {
  Metadata2<-filter(Metadata2, Experiment == "Pig_feces_2")
} else if (i=="P2spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_2_spiked")
} else if (i=="P2unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Pig_feces_2")
} else if (i=="S1") {
  Metadata2<-filter(Metadata2, Experiment == "Sewage_1")
} else if (i=="S1spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_1_spiked")
} else if (i=="S1unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_1")
} else if (i=="S2") {
  Metadata2<-filter(Metadata2, Experiment == "Sewage_2")
} else if (i=="S2spiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_2_spiked")
} else if (i=="S2unspiked") {
  Metadata2<-filter(Metadata2, Sample_type == "Sewage_2")
} else if (i=="All") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Further subsetting Metadata2
if (SubExp=="HX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment")
} else if (SubExp=="FTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Freeze_thaw_experiment")
} else if (SubExp=="LTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="LPSX") {
  Metadata22<-filter(Metadata2, Experiment_type == "Library_prep_seq_platform_experiment")
  VectorLPSX <- unique(Metadata22$Matching_samples)
  Metadata2<-filter(Metadata2, Matching_samples %in% VectorLPSX)
  rm(VectorLPSX, Metadata22)
} else if (SubExp=="HXFTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Freeze_thaw_experiment")
} else if (SubExp=="HXLTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="HXLPSX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Library_prep_seq_platform_experiment")
} else if (SubExp=="HXLTXLPSX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Long_term_storage_experiment" | Experiment_type == "Library_prep_seq_platform_experiment")
} else if (SubExp=="HXFTXLTX") {
  Metadata2<-filter(Metadata2, Experiment_type == "Handling_experiment" | Experiment_type == "Freeze_thaw_experiment" | Experiment_type == "Long_term_storage_experiment")
} else if (SubExp=="All") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Further subsetting Metadata2
if (SubFre=="Frozen") {
  Metadata2<-filter(Metadata2, FrozenUnfrozenSimple == "Freezer")
} else if (SubFre=="Unfrozen") {
  Metadata2<-filter(Metadata2, FrozenUnfrozenSimple == "Unfrozen")
} else if (SubFre=="Both") {
  print("No subsetting, all included")
} else {
  print("Subset defined not valid")
}

#Applying subsetting to OTU tables 
Tax2<-select(Tax, one_of(Metadata2$Sample))

#5.1 collapse analysis to P1... by removing spiked in orgs. 
##Remove spiked in orgs at genus level
#SpikedGenus<-c("Escherichia", "Bacteroides", "Salmonella", "Fusobacterium", "Propionibacterium", "Staphylococcus", "Cryptosporidium", "Saccharomyces")
#Tax2$Orgs<-rownames(Tax2)
#Tax2<-Tax2[!Tax2$Orgs %in% SpikedGenus, ]
#Tax2<-Tax2[, 1:length(Tax2)-1]

#Remake proportions
#Tax2<-sweep(Tax2, 2, colSums(Tax2), FUN="/")

RankAbun.1 <- rankabundance(t(Tax2))
RankAbun.1
write.table(data.frame(RankAbun.1), file=paste(i, "Rank", "Genus", ".txt", sep=""), sep="\t", dec=",", row.names = T, quote = F)

#Create RACplot
rankabunplot(RankAbun.1, scale='proportion', addit=FALSE, specnames=c(1,2,3), xlim=c(0,60), main=i)


}
dev.off()

```


## Additional
### Session information
```{r session_info}
sessionInfo()
```

### This document was processed on: 
```{r}
Sys.Date()
```

